#pragma once
#include <iostream>

enum symbols
{
	UNDEFINED = -INT_MAX, NUMBER_OF_SYMBOLS = -19,
	LAMBDA, QUOTE, DEFINE, CDR, CAR, ELSE, COND, CONS, 
	isNULL, isSYMBOL, isNUMBER, TIMES, MINUS, PLUS, FALSE, TRUE, 
	RIGHT_PAREN, LEFT_PAREN,
	NIL
};